const routes = {
  Home: 'Home',
  SignUpScreen: 'SignUpScreen',
  MySetting: 'MySetting',
  MyAccount: 'My Account',
  NGOProfile: 'NGOProfile',
  DownloadCertificate: 'DownloadCertificate',
  WelcomeScreen: 'WelcomeScreen',
  LoginScreen: 'LoginScreen',
  Dashboard: 'Dashboard',
  AddAddress: 'AddAddress',
  ForgetPassword: 'ForgetPassword',
  VerifyOtp: 'VerifyOtp',
  History: 'History',
  TabBar: 'TabBar',
  Maps: 'Maps',
  ForgotPassword: 'ForgotPassword',
  VerifyEmail: 'VerifyEmail',
  Certificate:'Certificate',
  BlogView: 'BlogView',
};
export default routes;
