const images = {
  logo: require('./images/logo.png'),
  logout: require('./images/logout.png'),
  success: require('./images/success.png'),
  error: require('./images/error.png'),
  news: require('./images/news.jpg'),
  locationIcon: require('./images/location.png'),
  notificationIcon: require('./images/notificationIcon.png'),
  searchIcon: require('./images/searchIcon.png'),
  speechIcon: require('./images/speechIcon.png'),
  currentLocation: require('./images/CurrentLocation.png'),
  plus: require('./images/plus.png'),
  home: require('./images/home.png'),
  settings: require('./images/settings.png'),
  history: require('./images/history.png'),
  homeSelected: require('./images/homeSelected.png'),
  settingsSelected: require('./images/settingsSelected.png'),
  historySelected: require('./images/historySelected.png'),
  greenTik: require('./images/tik.png'),
  shipped: require('./images/shipped.png'),
  packed: require('./images/packed.png'),
  notGreenTik: require('./images/notDistributed.png'),
  notCertified: require('./images/notCertified.png'),
  certified: require('./images/certified.png'),
  cancel: require('./images/cancel.png'),
  locationBlack: require('./images/locationBlack.png'),
  profile: require('./images/profile.jpg'),
  meal: require('./images/meals.png'),
  locationGray: require('./images/locationGray.png'),
  truckGray: require('./images/truckGray.png'),
  packedGray: require('./images/packedGray.png'),
  commentGray: require('./images/commentGray.png'),
  clockGray: require('./images/clockGray.png'),
  cloth:require('./images/cloths.png'),
  notReceived:require('./images/notReceived.png'),
  notCollected:require('./images/notCollected.png'),
  delayed:require('./images/delayed.png'),
  notDelayed:require('./images/notDelayed.png'),
  upload:require('./images/upload.png'),
  blog:require('./images/blog.jpg'),
  blog1:require('./images/blog1.webp'),
  blog2:require('./images/blog2.jpeg'),
  blog3:require('./images/blog3.jpeg'),
  certificate:require('./images/certificate.jpg'),
  calender:require('./images/calculator.png'),
  eyeGray:require('./images/eyeGray.png'),
  

};

export default images;
