name: Build React Native Android

on:
  push:
    branches:
      - test/testWithSecrets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - run: npm install -g yarn@1.22.19
      - name: Install Dependencies
        run: |
          yarn install
          
      - name: Check Node.js and Yarn version
        run: |
          node --version
          yarn --version
          npx react-native --version
          java --version


      - name: Update Google Services JSON and AndroidManifest.xml
        run: |
        # Update google-services.json
        sed -i "s|\\\${{secrets.PROJECT_NUMBER}}|${{secrets.PROJECT_NUMBER}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.PROJECT_ID}}|${{secrets.PROJECT_ID}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.STORAGE_BUCKET}}|${{secrets.STORAGE_BUCKET}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.MOBILESDK_APP_ID}}|${{secrets.MOBILESDK_APP_ID}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.PACKAGE_NAME}}|${{secrets.PACKAGE_NAME}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.CLIENT_ID}}|${{secrets.CLIENT_ID}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.CURRENT_KEY}}|${{secrets.CURRENT_KEY}}|g" android/app/google-services.json
        sed -i "s|\\\${{secrets.CLIENT_ID_IOS}}|${{secrets.CLIENT_ID_IOS}}|g" android/app/google-services.json

        # Update AndroidManifest.xml
        sed -i "s|\\\${{secrets.API_KEY}}|${{secrets.API_KEY}}|g" android/app/src/main/AndroidManifest.xml

        # Print the contents to temporary files
        echo "$(cat android/app/google-services.json)" > /tmp/google-services-updated.json
        echo "$(cat android/app/src/main/AndroidManifest.xml)" > /tmp/AndroidManifest-updated.xml

        # Display the updated contents
        cat /tmp/google-services-updated.json
        cat /tmp/AndroidManifest-updated.xml


      - name: Google Services
        run: |
          cat android/app/google-services.json 

      - name: Build Android
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
