name: Build React Native Android

on:
  push:
    branches:
      - test/testWithSecrets
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your other steps..
      - name: Create google-services.json
        run: cat android/app/src/main/AndroidManifest.xml
        env:
          API_KEY: ${{ secrets.API_KEY }}
          # PROJECT_ID: ${{ secrets.PROJECT_ID }}
          # STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          # MOBILESDK_APP_ID: ${{ secrets.MOBILESDK_APP_ID }}
          # PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          # CLIENT_ID: ${{ secrets.CLIENT_ID }}
          # CURRENT_KEY: ${{ secrets.CURRENT_KEY }}
          # CLIENT_ID_IOS: ${{ secrets.CLIENT_ID_IOS }}

      # - name: Print API Key from file
      #   run: cat android/app/google-services.json

      # - name: Upload API Key artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: api_key
      #     path: android/app/google-services.json

      