name: Build React Native Android

on:
  push:
    branches:
      - test/testWithSecrets
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your other steps...

     - name: Print API Key
        run: echo "::group::API Key\n${{ secrets.API_KEY }}\n::endgroup::"
        env:
          API_KEY: ${{ secrets.API_KEY }}