name: Build React Native Android

on:
  push:
    branches:
      - test/testWithSecrets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0  # Use the version from your local machine

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Check Node.js version
        run: |
          node --version
          npm --version
          npx react-native --version
          java --version

      - name: Google Services
        run: |
          cat android/app/google-services.json 

      - name: Build Android
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
