name: Build React Native Android

on:
  push:
    branches:
      - test/testWithSecrets
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your other steps..

      - name: Example Step
        run: echo "::group::API Key\n${{ secrets.API_KEY }}\n::endgroup::"
        env:
          APT_KEY: ${{ secrets.API_KEY }}

      - name: Example Step 2
        run: echo "${{ secrets.API_KEY }}" > api_key.txt
        env:
          APT_KEY: ${{ secrets.API_KEY }}

      - name: Example Step 3
        run: cat api_key.txt